Repository blish-hud/Blish-HUD, pull requests merged in 2019-08, with the labels that each got.

#80 Changed RasterizerState to CullNone
  Blish HUD/Entities/World.cs
Labels: bug

#93 Fix default trail width.
  Blish HUD/Pathing/Entities/ScrollingTrail.cs
Labels: bug

#90 Minor cleanup to the GameIntegrationService and the InputService
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/GameServices/Input/HookExtern.cs
  Blish HUD/GameServices/Input/KeyboardHook.cs
  Blish HUD/GameServices/Input/MouseEvent.cs
  Blish HUD/GameServices/Input/MouseHook.cs
  Blish HUD/GameServices/InputService.cs
Labels: cleanup

#94 added self as a player field
  Blish HUD/GameServices/ArcDps/Common/CommonFields.cs
Labels: feature

#98 Moved service directories from the root directory into the GameServices directory
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/Content/AsyncTexture2D.cs
  Blish HUD/GameServices/Content/DirectoryReader.cs
  Blish HUD/GameServices/Content/IDataReader.cs
  Blish HUD/GameServices/Content/Serialization/SemVerConverter.cs
  Blish HUD/GameServices/Content/ZipArchiveReader.cs
  Blish HUD/GameServices/Modules/Managers/ContentsManager.cs
  Blish HUD/GameServices/Modules/Managers/DirectoriesManager.cs
  Blish HUD/GameServices/Modules/Managers/Gw2ApiManager.cs
  Blish HUD/GameServices/Modules/Managers/SettingsManager.cs
  Blish HUD/GameServices/Modules/ManifestV1.cs
  Blish HUD/GameServices/Modules/Module.cs
  Blish HUD/GameServices/Modules/ModuleParameters.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/Activator.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/Always.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/BehaviorActivatorAttribute.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/ZoneActivator.cs
  Blish HUD/GameServices/Pathing/Behaviors/Bounce.cs
  Blish HUD/GameServices/Pathing/Behaviors/Copy.cs
  Blish HUD/GameServices/Pathing/Behaviors/DisplayInteractionInfo.cs
  Blish HUD/GameServices/Pathing/Behaviors/ILoadableBehavior.cs
  Blish HUD/GameServices/Pathing/Behaviors/Interactable[TPathable,TEntity].cs
  Blish HUD/GameServices/Pathing/Behaviors/Mesh.cs
  Blish HUD/GameServices/Pathing/Behaviors/Notification.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehavior.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehaviorAttribute.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehavior[TPathable,TEntity].cs
  Blish HUD/GameServices/Pathing/Behaviors/Rotate.cs
  Blish HUD/GameServices/Pathing/Behaviors/Title.cs
  Blish HUD/GameServices/Pathing/Behaviors/_Types/BehaviorWhen.cs
  Blish HUD/GameServices/Pathing/Content/PathableResourceManager.cs
  Blish HUD/GameServices/Pathing/Entities/Effects/MarkerEffect.cs
  Blish HUD/GameServices/Pathing/Entities/Marker.cs
  Blish HUD/GameServices/Pathing/Entities/ScrollingTrail.cs
  Blish HUD/GameServices/Pathing/Entities/ScrollingTrailSection.cs
  Blish HUD/GameServices/Pathing/Entities/Trail.cs
  Blish HUD/GameServices/Pathing/Format/LoadedMarkerPathable.cs
  Blish HUD/GameServices/Pathing/Format/LoadedPathable.cs
  Blish HUD/GameServices/Pathing/Format/LoadedTrailPathable.cs
  Blish HUD/GameServices/Pathing/IPathable.cs
  Blish HUD/GameServices/Pathing/ManagedPathable.cs
  Blish HUD/GameServices/Pathing/Markers/BasicMarkerPathable.cs
  Blish HUD/GameServices/Pathing/Markers/IMarker.cs
  Blish HUD/GameServices/Pathing/PathableAttribute.cs
  Blish HUD/GameServices/Pathing/PathableAttributeCollection.cs
  Blish HUD/GameServices/Pathing/Trails/BasicTrailPathable.cs
  Blish HUD/GameServices/Pathing/Trails/ITrail.cs
  Blish HUD/GameServices/Pathing/Trails/Route.cs
Labels: cleanup

#99 couple of control fixes.
  Blish HUD/Blish HUD.csproj
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/CornerIcon.cs
  Blish HUD/Controls/LoadingSpinner.cs
  Blish HUD/Controls/Menu.cs
  Blish HUD/Controls/TabbedWindow.cs
  Blish HUD/Controls/WindowTab.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/_Utils/DrawUtil.cs
  Blish HUD/_Utils/LoadingSpinnerUtil.cs
Labels: cleanup

#104 Fix crash when registry path not defined
  Blish HUD/GameServices/GameIntegrationService.cs
Labels: bug, gameservice

#105 Static chat code service, changed IKeyboard
  Blish HUD/Blish HUD.csproj
  Blish HUD/Common/Gw2/ChatCode.cs
  Blish HUD/Controls/Extern/VirtualKeyShort.cs
  Blish HUD/Controls/Intern/Keyboard.cs
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/_Interfaces/IKeyboard.cs
Labels: breaking change, cleanup

#112 Upwards dropdown
  Blish HUD/Controls/Dropdown.cs
Labels: UI, cleanup, feature
