Repository blish-hud/Blish-HUD, pull requests merged in 2019-09, with the labels that each got.

#120 Fixes ToLower culture not specified
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/Pathing/Behaviors/Bounce.cs
  Blish HUD/GameServices/Pathing/Behaviors/Copy.cs
  Blish HUD/GameServices/Pathing/Behaviors/Mesh.cs
  Blish HUD/GameServices/Pathing/Behaviors/Notification.cs
  Blish HUD/GameServices/Pathing/Behaviors/Rotate.cs
  Blish HUD/GameServices/Pathing/Behaviors/Title.cs
Labels: bug

#106 Contexts + CdnInfoContext & Gw2ClientContext
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/Contexts/CdnInfoContext.cs
  Blish HUD/GameServices/Contexts/Context.cs
  Blish HUD/GameServices/Contexts/ContextAvailability.cs
  Blish HUD/GameServices/Contexts/ContextResult[T].cs
  Blish HUD/GameServices/Contexts/ContextState.cs
  Blish HUD/GameServices/Contexts/Gw2ClientContext.cs
  Blish HUD/GameServices/ContextsService.cs
  Blish HUD/GameServices/GameService.cs
  Blish HUD/GameServices/Gw2MumbleService.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/Properties/Strings.Designer.cs
  Blish HUD/Properties/Strings.resx
Labels: feature

#121 Modified control invalidation for better control updates
  Blish HUD/Controls/Checkbox.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/InteractionIndicator.cs
  Blish HUD/Controls/Label.cs
  Blish HUD/Controls/LabelBase.cs
Labels: bug

#122 Added BackgroundTexture property to Panels.
  Blish HUD/Controls/Panel.cs
Labels: UI, feature

#127 Added support for "bounce-distance" attribute on markers.
  Blish HUD/GameServices/Pathing/Behaviors/Bounce.cs
Labels: feature

#129 Added "notification-distance" attribute
  Blish HUD/GameServices/Pathing/Behaviors/Notification.cs
Labels: feature
