Repository blish-hud/Blish-HUD, pull requests merged in 2020-06, with the labels that each got.

#241 Setting Renderers, FlowPanel Improvements, and Setting/About Views
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/FlowPanel.cs
  Blish HUD/Controls/KeybindingAssigner.cs
  Blish HUD/Controls/Panel.cs
  Blish HUD/Controls/ViewContainer.cs
  Blish HUD/Controls/_Types/SizingMode.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/GameServices/Overlay/UI/Views/OverlaySettingsView.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/Settings/SettingCollection.cs
  Blish HUD/GameServices/Settings/SettingEntry.cs
  Blish HUD/GameServices/Settings/SettingEntry[T].cs
  Blish HUD/GameServices/Settings/UI/AboutUIBuilder.cs
  Blish HUD/GameServices/Settings/UI/OverlaySettingsUIBuilder.cs
  Blish HUD/GameServices/Settings/UI/Presenters/SettingPresenter.cs
  Blish HUD/GameServices/Settings/UI/UpdateUIBuilder.cs
  Blish HUD/GameServices/Settings/UI/Views/BoolSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/EnumSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/EnumSettingView[T].cs
  Blish HUD/GameServices/Settings/UI/Views/KeybindingSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingView[T].cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsView.cs
  Blish HUD/GameServices/Settings/UI/Views/StringSettingView.cs
  Blish HUD/GameServices/SettingsService.cs
  Blish HUD/Properties/launchSettings.json
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.de.resx
  Blish HUD/Strings/GameServices/OverlayService.es.resx
  Blish HUD/Strings/GameServices/OverlayService.fr.resx
  Blish HUD/Strings/GameServices/OverlayService.resx
  Blish HUD/_Utils/ControlUtil.cs
Labels: UI, cleanup, feature

#242 Corrected English translation for "Manage API-Keys" and fixed German translations
  Blish HUD/Strings/GameServices/Gw2ApiService.Designer.cs
  Blish HUD/Strings/GameServices/Gw2ApiService.de.resx
  Blish HUD/Strings/GameServices/Gw2ApiService.resx
Labels: cleanup

#244 SettingRender fixes, scrollbar fixes, and locale event wiring.
  Blish HUD/Controls/Panel.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/Settings/SettingCollection.cs
  Blish HUD/GameServices/Settings/SettingEntry.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsView.cs
Labels: UI, bug

#245 API View & Scrollbar fixes
  Blish HUD/Controls/Panel.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Presenters/ApiTokenPresenter.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/ApiTokenView.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/RegisterApiKeyView.cs
  Blish HUD/Strings/GameServices/Gw2ApiService.Designer.cs
  Blish HUD/Strings/GameServices/Gw2ApiService.resx
Labels: UI, bug

#247 Multibox Support
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/Program.cs
Labels: feature

#252 Support Module Localization
  Blish HUD/GameServices/Modules/ModuleManager.cs
Labels: feature, module

#255 Handle EntryPoint OnUserFacingException and OnHelpInvoked
  Blish HUD/ApplicationSettings.cs
  Blish HUD/Program.cs
Labels: bug

#259 OverlayService and Gw2ClientContext Improvements
  Blish HUD/GameServices/Contexts/Gw2ClientContext.cs
  Blish HUD/GameServices/OverlayService.cs
Labels: cleanup

#258 Dropdown (and some Tooltip) Improvements
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/Dropdown.cs
  Blish HUD/Controls/Screen.cs
  Blish HUD/Controls/Tooltip.cs
Labels: UI, feature

#257 ContextMenuStrip Improvements
  Blish HUD/Controls/ContextMenuStrip.cs
Labels: bug, feature

#253 added idea folder to gitignore
  .gitignore
  .idea/.idea.Blish HUD/.idea/.idea.Blish HUD.iml
  .idea/.idea.Blish HUD/.idea/indexLayout.xml
  .idea/.idea.Blish HUD/.idea/modules.xml
  .idea/.idea.Blish HUD/.idea/projectSettingsUpdater.xml
  .idea/.idea.Blish HUD/riderModule.iml
Labels: cleanup

#261 Stop rate-limiting the render service
  Blish HUD/GameServices/Gw2WebApiService.cs
Labels: bug, cleanup

#266 Fixed displaying selected item in Dropdown.
  Blish HUD/Controls/Dropdown.cs
Labels: bug

#265 Refresh Gw2Process on exception
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/_Utils/WindowUtil.cs
Labels: bug
