Repository blish-hud/Blish-HUD, pull requests merged in 2021-12, with the labels that each got.

#552 Prevent initial keybinding from being null on KeybindingAssigner.
  Blish HUD/Controls/KeybindingAssigner.cs
  Blish HUD/GameServices/OverlayService.cs
Labels: bug

#548 feat/dynamic-hud
  Blish HUD/Controls/CornerIcon.cs
  Blish HUD/GameServices/Overlay/DynamicHUDMethod.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.resx
Labels: bug, feature

#554 Extended some of what contingency handles + minor serialization corrections
  Blish HUD/GameServices/Debug/Contingency.cs
  Blish HUD/GameServices/Modules/ManifestV1.cs
  Blish HUD/GameServices/Modules/ModuleDependency.cs
  Blish HUD/_Utils/DirectoryUtil.cs
Labels: bug, feature

#558 Prevent duplicate setting definitions
  Blish HUD/GameServices/Settings/SettingCollection.cs
Labels: bug

#559 Manual incompatibility listing.
  Blish HUD/GameServices/ModuleService.cs
  Blish HUD/ref/compatibility.json
Labels: feature, gameservice
