Repository blish-hud/Blish-HUD, pull requests merged in 2021-08, with the labels that each got.

#402 Lock container children
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/ContextMenuStrip.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/DetailsButton.cs
  Blish HUD/Controls/FlowPanel.cs
  Blish HUD/Controls/Menu.cs
  Blish HUD/Controls/MenuItem.cs
  Blish HUD/Controls/_Events/ChildChangedEventArgs.cs
  Blish HUD/Controls/_Types/ControlCollection.cs
Labels: ++patch, UI, breaking change, bug

#410 Fix for CTRL+ALT key combinations ...
  Blish HUD/Controls/TextInputBase.cs
Labels: bug

#409 Tooltip refresh
  Blish HUD/Common/UI/Views/BasicTooltipView.cs
  Blish HUD/Common/UI/Views/ITooltipView.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/Tooltip.cs
  Blish HUD/Controls/ViewContainer.cs
  Blish HUD/Controls/_Types/IViewContainer.cs
  Blish HUD/GameServices/Graphics/UI/View.cs
Labels: ++patch, UI, bug

#413 Updated tray area icon.
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/GameIntegration/WinFormsIntegration.cs
  Blish HUD/Properties/Resources.Designer.cs
  Blish HUD/Properties/Resources.resx
  Blish HUD/Resources/2039771.ico
Labels: UI

#412 Form and idle fixes
  Blish HUD/BlishHud.cs
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/GameServices/OverlayService.cs
Labels: bug, ++patch

#415 Corrected multiple mouse capture issues
  Blish HUD/Controls/Checkbox.cs
  Blish HUD/Controls/ColorBox.cs
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/ContextMenuStrip.cs
  Blish HUD/Controls/ContextMenuStripItem.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/CornerIcon.cs
  Blish HUD/Controls/DetailsButton.cs
  Blish HUD/Controls/Dropdown.cs
  Blish HUD/Controls/GlowButton.cs
  Blish HUD/Controls/HealthPoolButton.cs
  Blish HUD/Controls/KeybindingAssigner.cs
  Blish HUD/Controls/LabelBase.cs
  Blish HUD/Controls/MenuItem.cs
  Blish HUD/Controls/Screen.cs
  Blish HUD/Controls/ScreenNotification.cs
  Blish HUD/Controls/StandardButton.cs
  Blish HUD/Controls/TabbedWindow.cs
  Blish HUD/Controls/TextInputBase.cs
  Blish HUD/Controls/TrackBar.cs
  Blish HUD/Controls/WindowBase.cs
  Blish HUD/GameServices/Input/Mouse/MouseHandler.cs
Labels: bug, gameservice, ++patch

#417 Fix input events not triggering when not over hud.
  Blish HUD/GameServices/Input/Mouse/MouseHandler.cs
Labels: bug
