Repository blish-hud/Blish-HUD, pull requests merged in 2021-10, with the labels that each got.

#481 Swap implementation of CSCore to NAudio
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/GameIntegration/AudioEndpointNotificationReceiver.cs
  Blish HUD/GameServices/GameIntegration/AudioIntegration.cs
Labels: feature, breaking change

#489 Keyboard not blocked
  Blish HUD/Controls/KeybindingAssignmentWindow.cs
  Blish HUD/GameServices/Input/Keyboard/KeyBinding.cs
  Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
Labels: bug

#494 Add subtoken event
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/Modules/Managers/Gw2ApiManager.cs
Labels: WIP

#490 Fix numeric settings clamping values before compliance is applied.
  Blish HUD/GameServices/Settings/UI/Views/FloatSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/IntSettingView.cs
Labels: bug
