Repository blish-hud/Blish-HUD, pull requests merged in 2021-09, with the labels that each got.

#425 Ensure parent can't be null when calculating absoluteopacity or absolutebounds
  Blish HUD/Controls/Control.cs
Labels: bug

#429 Fixed tooltip vertical offset when above the mouse.
  Blish HUD/Controls/Tooltip.cs
Labels: bug, UI

#432 Make sure that the cancellation token is not null
  Blish HUD/GameServices/ArcDps/SocketListener/SocketListener.cs
Labels: bug

#431 Ensure compliance is applied prior to values.
  Blish HUD/GameServices/Settings/UI/Presenters/SettingPresenter.cs
Labels: bug

#433 Render service now fails gracefully
  Blish HUD/GameServices/Content/AsyncTexture2D.cs
  Blish HUD/GameServices/ContentService.cs
Labels: bug

#418 Window construction improvements
  Blish HUD/Common/UI/Views/BasicTooltipView.cs
  Blish HUD/Common/UI/Views/StaticPanelView.cs
  Blish HUD/Controls/BasicWindow.cs
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/Screen.cs
  Blish HUD/Controls/StandardWindow.cs
  Blish HUD/Controls/TabbedWindow.cs
  Blish HUD/Controls/TabbedWindow2.cs
  Blish HUD/Controls/Tooltip.cs
  Blish HUD/Controls/WindowBase.cs
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/Controls/WindowTab.cs
  Blish HUD/Controls/_Events/ChildChangedEventArgs.cs
  Blish HUD/Controls/_Types/IAccordion.cs
  Blish HUD/Controls/_Types/ICheckable.cs
  Blish HUD/Controls/_Types/ITabOwner.cs
  Blish HUD/Controls/_Types/IWindow.cs
  Blish HUD/Controls/_Types/Tab.cs
  Blish HUD/Controls/_Types/TabCollection.cs
  Blish HUD/GameServices/Graphics/UI/IView.cs
  Blish HUD/GameServices/Graphics/UI/View.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/ApiTokenView.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/RegisterApiKeyView.cs
  Blish HUD/GameServices/Modules/UI/Views/ManageModuleView.cs
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
  Blish HUD/GameServices/Modules/UI/Views/ModuleRepoView.cs
  Blish HUD/GameServices/Modules/UI/Views/NoModulesView.cs
  Blish HUD/GameServices/Modules/UI/Views/TitledDetailView.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/GameServices/Overlay/UI/Views/OverlaySettingsView.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/Settings/UI/Views/BoolSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/EnumSettingView[T].cs
  Blish HUD/GameServices/Settings/UI/Views/FloatSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/KeybindingSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/NumericSettingView.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingView[T].cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsMenuView.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsView.cs
  Blish HUD/GameServices/Settings/UI/Views/StringSettingView.cs
  Blish HUD/ref/605026.png
Labels: UI, breaking change, cleanup, ++minor

#435 Ensure we don't render on desktop if game is minimized
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/_Utils/WindowUtil.cs
Labels: bug

#436 Support custom setting panels
  Blish HUD/GameServices/Modules/Module.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ManageModulePresenter.cs
  Blish HUD/GameServices/Modules/UI/Views/ManageModuleView.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsMenuView.cs
Labels: feature, gameservice, ++minor

#438 Window bugs
  Blish HUD/Controls/StandardWindow.cs
  Blish HUD/Controls/TabbedWindow2.cs
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/Controls/_Types/Tab.cs
  Blish HUD/Controls/_Types/TabCollection.cs
  Blish HUD/GameServices/Settings/UI/Views/SettingsView.cs
Labels: bug

#437 Modification to frame limiter options
  Blish HUD/BlishHud.cs
  Blish HUD/GameServices/Graphics/FramerateMethod.cs
  Blish HUD/GameServices/GraphicsService.cs
  Blish HUD/GameServices/Gw2MumbleService.cs
Labels: bug, gameservice

#439 Only let the submenu open if the control is enabled.
  Blish HUD/Controls/ContextMenuStripItem.cs
Labels: bug

#440 Add timer to each module update for debug display.
  Blish HUD/GameServices/ModuleService.cs
Labels: feature

#441 Allow using a custom Tooltip for CornerIcon
  Blish HUD/Controls/CornerIcon.cs
Labels: UI

#443 Feature #70: Close active window on escape.
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/Controls/_Types/IWindow.cs
  Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
Labels: feature, UI

#450 Ensure subcollection views are visible with autosizing.
  Blish HUD/GameServices/Settings/UI/Views/SettingsView.cs
Labels: bug, UI

#461 Ensured OnEnabled and OnDisabled worked.
  Blish HUD/GameServices/InputService.cs
Labels: bug

#463 Fix for crash while gw2 is closing
  Blish HUD/GameServices/GameIntegration/Gw2InstanceIntegration.cs
Labels: bug

#466 Gw2Sharp 1.3.0
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/Gw2WebApi/UI/Presenters/ApiTokenPresenter.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/ApiTokenView.cs
  Blish HUD/GameServices/Gw2WebApiService.cs
Labels: bug, gameservice, ++patch

#469 Fix for #468
  Blish HUD/GameServices/GameIntegration/Gw2InstanceIntegration.cs
Labels: bug

#479 DPI Support on legacy OS's
  Blish HUD/GameServices/GraphicsService.cs
Labels: bug

#480 Avoid crashing if we fail to pull env details from the gw2 process.
  Blish HUD/GameServices/GameIntegration/Gw2InstanceIntegration.cs
Labels: bug
