Repository blish-hud/Blish-HUD, pull requests merged in 2021-07, with the labels that each got.

#384 Multiple minor window improvements
  Blish HUD/Controls/TabbedWindow.cs
  Blish HUD/Controls/WindowBase.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/Settings/SettingCollection.cs
Labels: bug, feature

#386 Rewrite ArcDps networking code for clarity
  Blish HUD/GameServices/ArcDps/AsyncUserToken.cs
  Blish HUD/GameServices/ArcDps/SocketListener/SocketListener.cs
  Blish HUD/GameServices/ArcDpsService.cs
Labels: cleanup

#388 Add support for configurable bhm output file name
  Blish HUD/build/BlishHUD.targets
Labels: feature, module

#397 Fix operator typo and doc
  Blish HUD/GameServices/GameIntegrationService.cs
Labels: bugfix, gameservice

#395 Finally remove old pathing service / entity classes / persistent store services
  Blish HUD/Entities/Cube.cs
  Blish HUD/Entities/Entity.cs
  Blish HUD/Entities/EntityBillboard.cs
  Blish HUD/Entities/EntityText.cs
  Blish HUD/Entities/Primitives/Billboard.cs
  Blish HUD/Entities/Primitives/Cuboid.cs
  Blish HUD/Entities/Primitives/Face.cs
  Blish HUD/Entities/Primitives/Mesh.cs
  Blish HUD/GameServices/GameService.cs
  Blish HUD/GameServices/Modules/ModuleManager.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ManageModulePresenter.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/Activator.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/Always.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/BehaviorActivatorAttribute.cs
  Blish HUD/GameServices/Pathing/Behaviors/Activator/ZoneActivator.cs
  Blish HUD/GameServices/Pathing/Behaviors/Bounce.cs
  Blish HUD/GameServices/Pathing/Behaviors/Copy.cs
  Blish HUD/GameServices/Pathing/Behaviors/DisplayInteractionInfo.cs
  Blish HUD/GameServices/Pathing/Behaviors/ILoadableBehavior.cs
  Blish HUD/GameServices/Pathing/Behaviors/Interactable[TPathable,TEntity].cs
  Blish HUD/GameServices/Pathing/Behaviors/Notification.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehavior.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehaviorAttribute.cs
  Blish HUD/GameServices/Pathing/Behaviors/PathingBehavior[TPathable,TEntity].cs
  Blish HUD/GameServices/Pathing/Behaviors/Rotate.cs
  Blish HUD/GameServices/Pathing/Behaviors/Tint.cs
  Blish HUD/GameServices/Pathing/Behaviors/Title.cs
  Blish HUD/GameServices/Pathing/Behaviors/_Types/BehaviorWhen.cs
  Blish HUD/GameServices/Pathing/Content/PathableResourceManager.cs
  Blish HUD/GameServices/Pathing/Entities/Effects/MarkerEffect.cs
  Blish HUD/GameServices/Pathing/Entities/Effects/TrailEffect.cs
  Blish HUD/GameServices/Pathing/Entities/Marker.cs
  Blish HUD/GameServices/Pathing/Entities/ScrollingTrail.cs
  Blish HUD/GameServices/Pathing/Entities/ScrollingTrailSection.cs
  Blish HUD/GameServices/Pathing/Entities/Trail.cs
  Blish HUD/GameServices/Pathing/Format/LoadedMarkerPathable.cs
  Blish HUD/GameServices/Pathing/Format/LoadedPathable.cs
  Blish HUD/GameServices/Pathing/Format/LoadedTrailPathable.cs
  Blish HUD/GameServices/Pathing/IPathable.cs
  Blish HUD/GameServices/Pathing/ManagedPathable.cs
  Blish HUD/GameServices/Pathing/Markers/BasicMarkerPathable.cs
  Blish HUD/GameServices/Pathing/Markers/IMarker.cs
  Blish HUD/GameServices/Pathing/PathableAttribute.cs
  Blish HUD/GameServices/Pathing/PathableAttributeCollection.cs
  Blish HUD/GameServices/Pathing/Trails/BasicTrailPathable.cs
  Blish HUD/GameServices/Pathing/Trails/ITrail.cs
  Blish HUD/GameServices/Pathing/Trails/Route.cs
  Blish HUD/GameServices/PathingService.cs
  Blish HUD/GameServices/PersistentStore/Store.cs
  Blish HUD/GameServices/PersistentStore/StoreValue.cs
  Blish HUD/GameServices/PersistentStore/StoreValue[T].cs
  Blish HUD/GameServices/PersistentStoreService.cs
Labels: breaking change, cleanup, gameservice

#400 Allow setting displaynames and descriptions to update when language is changed
  Blish HUD/GameServices/GameIntegration/AudioIntegration.cs
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/GameServices/GraphicsService.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/Settings/SettingCollection.cs
  Blish HUD/GameServices/Settings/SettingEntry.cs
  Blish HUD/GameServices/SettingsService.cs
Labels: breaking change, bug

#394 Change default repo provider from GitHub to pkgs.blishhud.com.
  Blish HUD/GameServices/Modules/Pkgs/GitHubPkgRepoProvider.cs
  Blish HUD/GameServices/Modules/Pkgs/PublicPkgRepoProvider.cs
  Blish HUD/GameServices/Modules/Pkgs/StaticPkgRepoProvider.cs
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
Labels: bug, feature, gameservice

#403 Disable inactive sleep time.
  Blish HUD/BlishHud.cs
Labels: bug
