Repository blish-hud/Blish-HUD, pull requests merged in 2022-09, with the labels that each got.

#711 Catch ArgumentException when trying to read the game process environment variables
  Blish HUD/GameServices/GameIntegration/Gw2InstanceIntegration.cs
Labels: bug

#741 Maint 0.11.9
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/Contexts/CdnInfoContext.cs
  Blish HUD/GameServices/Contexts/FestivalContext.cs
  Blish HUD/GameServices/GameIntegration/Gw2InstanceIntegration.cs
  Blish HUD/GameServices/GameIntegration/WinFormsIntegration.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/RegisterApiKeyView.cs
  Blish HUD/ref/compatibility.json
  Blish HUD/ref/metadata.gz
Labels: bug, cleanup

#742 Added spoiled module support to the module service.
  Blish HUD/GameServices/ModuleService.cs
  Blish HUD/Strings/GameServices/ModulesService.Designer.cs
  Blish HUD/Strings/GameServices/ModulesService.de.resx
  Blish HUD/Strings/GameServices/ModulesService.fr.resx
  Blish HUD/Strings/GameServices/ModulesService.resx
Labels: feature, gameservice

#748 About view revisions, Nvidia check extension, and README/License udpates.
  Blish HUD/Blish HUD.csproj
  Blish HUD/GameServices/Debug/ContingencyChecks.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/Strings/GameServices/Debug/ContingencyMessages.Designer.cs
  Blish HUD/Strings/GameServices/Debug/ContingencyMessages.resx
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.resx
  Blish HUD/ref/views/about/section-splitter.png
  LICENSE
  README.md
Labels: UI, cleanup

#756 Fixed click order for ContextMenuStripItem.
  Blish HUD/Controls/ContextMenuStripItem.cs
Labels: bug

#758 Updated private assets.
  Blish HUD/Blish HUD.csproj
Labels: cleanup

#762 Fixed restarting the game not keeping Blish HUD open.
  Blish HUD/Program.cs
Labels: bug

#763 Add TrackBar.IsDraggingChanged event
  Blish HUD/Controls/TrackBar.cs
Labels: feature

#770 🐛fix SettingsCollection.RenderInUi not being used in constructor
  Blish HUD/GameServices/Settings/SettingCollection.cs
Labels: cleanup

#766 Fix ScreenNotification location
  Blish HUD/Controls/ScreenNotification.cs
Labels: bug
