Repository blish-hud/Blish-HUD, pull requests merged in 2022-05, with the labels that each got.

#684 Fix MissingMethodExceptions with SuspendLayout changes
  Blish HUD/Controls/Control.cs
Labels: compatibility

#674 Fix submenu menu items not able to click.
  Blish HUD/Controls/ContextMenuStrip.cs
Labels: bug

#687 Split close on Escape out of CanClose
  Blish HUD/Controls/KeybindingAssignmentWindow.cs
  Blish HUD/Controls/WindowBase.cs
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/Controls/_Types/IWindow.cs
  Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
Labels: feature

#688 Add windowbase2 resize support
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/KeybindingAssignmentWindow.cs
  Blish HUD/Controls/StandardWindow.cs
  Blish HUD/Controls/TabbedWindow2.cs
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
Labels: feature

#692 Revise suspendlayout on flowpanel
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/FlowPanel.cs
Labels: bug
