Repository blish-hud/Blish-HUD, pull requests merged in 2022-03, with the labels that each got.

#621 Revised exception to ensure all API failures are caught and handled.
  Blish HUD/GameServices/Gw2WebApi/UI/Views/RegisterApiKeyView.cs
Labels: bug

#628 Update AudioIntegration.cs
  Blish HUD/GameServices/GameIntegration/AudioIntegration.cs
Labels: bug

#629 Update AudioIntegration.cs
  Blish HUD/GameServices/GameIntegration/AudioIntegration.cs
Labels: bug

#649 Fix #614 Add Selection dragging support to TextInputBase
  Blish HUD/Controls/TextInputBase.cs
Labels: feature

#644 Prerelease Changes
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/GameIntegrationService.cs
  Blish HUD/GameServices/GraphicsService.cs
  Blish HUD/GameServices/Input/Keyboard/KeyBinding.cs
  Blish HUD/GameServices/Input/Keyboard/KeyboardHandler.cs
  Blish HUD/GameServices/Modules/Managers/ContentsManager.cs
  Blish HUD/GameServices/Modules/ModulePkgRepoHandler.cs
  Blish HUD/GameServices/Modules/Pkgs/GitHubPkgRepoProvider.cs
  Blish HUD/GameServices/Modules/Pkgs/PkgManifest.cs
  Blish HUD/GameServices/Modules/Pkgs/StaticPkgRepoProvider.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ManagePkgPresenter.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ModuleRepoPresenter.cs
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
  Blish HUD/GameServices/Overlay/OverlayUpdateHandler.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/Strings/GameServices/ModulesService.Designer.cs
  Blish HUD/Strings/GameServices/ModulesService.resx
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.resx
  Blish HUD/_Extensions/Texture2DExtension.cs
  Blish HUD/_Utils/TextureUtil.cs
Labels: feature

#652 Feat/easy fixes
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
  Blish HUD/GameServices/Settings/SettingCollection.cs
Labels: bug, feature

#654 Add GraphicsDeviceContext helper struct + methods
  Blish HUD/GameServices/GraphicsDeviceContext.cs
  Blish HUD/GameServices/GraphicsService.cs
Labels: feature, gameservice

#655 Fix graphics device locking
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/GraphicsDeviceContext.cs
  Blish HUD/GameServices/GraphicsService.cs
  Blish HUD/GameServices/Modules/Managers/ContentsManager.cs
  Blish HUD/_Extensions/Texture2DExtension.cs
  Blish HUD/_Utils/TextureUtil.cs
Labels: bug

#658 Revised GraphicsDeviceContext namespace.
  Blish HUD/GameServices/Graphics/GraphicsDeviceContext.cs
Labels: cleanup
