Repository blish-hud/Blish-HUD, pull requests merged in 2022-06, with the labels that each got.

#696 Introducing: DatAssetCache
  .editorconfig
  Blish HUD/Controls/BackButton.cs
  Blish HUD/Controls/Book.cs
  Blish HUD/Controls/ContextMenuStripItem.cs
  Blish HUD/Controls/DetailsButton.cs
  Blish HUD/Controls/Menu.cs
  Blish HUD/Controls/MenuItem.cs
  Blish HUD/Controls/Panel.cs
  Blish HUD/Controls/TabbedWindow.cs
  Blish HUD/Controls/TrackBar.cs
  Blish HUD/Controls/WindowBase.cs
  Blish HUD/Controls/WindowBase2.cs
  Blish HUD/GameServices/Content/AsyncTexture2D.cs
  Blish HUD/GameServices/Content/DatAssetCache.cs
  Blish HUD/GameServices/Content/RenderServiceTextureSize.cs
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/ApiTokenView.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/RegisterApiKeyView.cs
  Blish HUD/GameServices/Gw2WebApiService.cs
  Blish HUD/GameServices/ModuleService.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ManageModulePresenter.cs
  Blish HUD/GameServices/Modules/UI/Views/ManageModuleView.cs
  Blish HUD/GameServices/Modules/UI/Views/ManagePkgView.cs
  Blish HUD/GameServices/Modules/UI/Views/ModuleRepoView.cs
  Blish HUD/GameServices/Modules/UI/Views/TitledDetailView.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/Controls/BouncyNotification.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/Controls/SelfUpdateWindow.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/_Utils/DirectoryUtil.cs
  Blish HUD/ref/metadata.gz
Labels: feature, WIP

#704 Write to temp settings file before swapping out the real one.
  Blish HUD/GameServices/SettingsService.cs
Labels: bug

#705 Prevent NRE when module fails to load and then attempts to unload.
  Blish HUD/GameServices/Modules/Module.cs
Labels: bug

#706 Ensure control parents are captured before null checks.
  Blish HUD/Controls/Container.cs
  Blish HUD/Controls/ContextMenuStripItem.cs
  Blish HUD/Controls/KeybindingAssignmentWindow.cs
Labels: bug

#707 Fix several smaller bugs
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  Blish HUD/Blish HUD.csproj
  Blish HUD/Controls/ContextMenuStrip.cs
  Blish HUD/GameServices/DebugService.cs
  Blish HUD/GameServices/Gw2WebApi/TokenBucket.cs
  Blish HUD/Library/Glide/Tweener.cs
Labels: bug

#691 FormattedLabel Control
  Blish HUD/Content/Content.mgcb
  Blish HUD/Controls/FormattedLabel.cs
  Blish HUD/Controls/_Types/FormattedLabelBuilder.cs
  Blish HUD/Controls/_Types/FormattedLabelPart.cs
  Blish HUD/Controls/_Types/FormattedLabelPartBuilder.cs
  Blish HUD/GameServices/ContentService.cs
Labels: feature, UI

#713 No restart on PID and fix for NRE
  Blish HUD/GameServices/Input/Mouse/MouseHandler.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/Program.cs
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.resx
Labels: bug, feature

#714 Revise locking path for same-thread access on the graphics device.
  Blish HUD/GameServices/GraphicsService.cs
Labels: bug
