Repository blish-hud/Blish-HUD, pull requests merged in 2022-01, with the labels that each got.

#571 Ensure scissor rectangle is properly scaled when a control is set to not clip bounds.
  Blish HUD/Controls/Control.cs
Labels: bug

#573 Updated README
  README.md
Labels: cleanup

#576 Add self-update support.
  Blish HUD/Blish HUD.csproj
  Blish HUD/Controls/ContextMenuStrip.cs
  Blish HUD/Controls/ContextMenuStripItem.cs
  Blish HUD/Controls/Control.cs
  Blish HUD/Controls/CornerIcon.cs
  Blish HUD/GameServices/ContentService.cs
  Blish HUD/GameServices/Debug/Contingency.cs
  Blish HUD/GameServices/Modules/ModulePkgRepoHandler.cs
  Blish HUD/GameServices/Overlay/CoreVersionManifest.cs
  Blish HUD/GameServices/Overlay/OverlayUpdateHandler.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/Controls/BouncyNotification.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/Controls/SelfUpdateWindow.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/SelfUpdateUtil.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
  Blish HUD/GameServices/OverlayService.cs
  Blish HUD/GameServices/SettingsService.cs
  Blish HUD/Library/Glide/Tween.cs
  Blish HUD/Program.cs
  Blish HUD/Strings/Common.Designer.cs
  Blish HUD/Strings/Common.resx
  Blish HUD/Strings/GameServices/Debug/ContingencyMessages.Designer.cs
  Blish HUD/Strings/GameServices/Debug/ContingencyMessages.resx
  Blish HUD/Strings/GameServices/OverlayService.Designer.cs
  Blish HUD/Strings/GameServices/OverlayService.resx
  Blish HUD/_Extensions/SpriteBatchExtensions.cs
  Blish HUD/ref/audio/hero-open.wav
  Blish HUD/ref/common/605016.png
  Blish HUD/ref/common/605017.png
  Blish HUD/ref/controls/bouncynotification/965696.png
  Blish HUD/ref/views/selfupdater/1235000.png
  Blish HUD/ref/views/selfupdater/744427-blue.png
  Blish HUD/ref/views/selfupdater/744428-blue.png
  Blish HUD/ref/views/selfupdater/hero-prerelease.png
  Blish HUD/ref/views/selfupdater/hero-release.png
  Blish HUD/ref/views/selfupdater/updateview.png
Labels: feature

#578 Fix/sonarcloud complaints
  Blish HUD/Controls/TrackBar.cs
  Blish HUD/GameServices/Modules/UI/Presenters/ManagePkgPresenter.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/Controls/SelfUpdateWindow.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/SelfUpdateUtil.cs
Labels: cleanup

#579 Make "MouseInHouse" only true if over the real icons to preserve the consistency.
  Blish HUD/Controls/CornerIcon.cs
Labels: bug

#585 Minor fixes
  Blish HUD/GameServices/GameIntegration/AudioIntegration.cs
  Blish HUD/GameServices/GameIntegration/GfxSettingsIntegration.cs
  Blish HUD/GameServices/OverlayService.cs
Labels: bug

#589 Add proper localization support to the gw2 api service views.
  Blish HUD/GameServices/Gw2WebApi/UI/Presenters/ApiTokenPresenter.cs
  Blish HUD/GameServices/Gw2WebApi/UI/Views/ApiTokenView.cs
  Blish HUD/Strings/GameServices/Gw2ApiService.Designer.cs
  Blish HUD/Strings/GameServices/Gw2ApiService.resx
Labels: UI

#592 Remove SyncWithGame option and fix restart.
  Blish HUD/GameServices/GraphicsService.cs
  Blish HUD/Program.cs
Labels: bug

#593 HorizontalAlignment.Right & .Center for TextBox
  Blish HUD/Controls/TextInputBase.cs
  Blish HUD/Controls/Textbox.cs
Labels: feature, UI
