Repository blish-hud/Blish-HUD, pull requests merged in 2023-01, with the labels that each got.

#820 Reverts some opacity changes.
  Blish HUD/BlishHud.cs
Labels: bug, cleanup

#830 fix module repo filter checkbox being inverted
  Blish HUD/GameServices/Modules/Pkgs/StaticPkgRepoProvider.cs
Labels: bug

#831 Module menu item improvements
  Blish HUD/GameServices/ModuleService.cs
  Blish HUD/GameServices/Modules/ModuleManager.cs
Labels: feature

#832 Revised enable/disabled display for modules in the listing
  Blish HUD/Controls/MenuItem.cs
  Blish HUD/GameServices/ModuleService.cs
  Blish HUD/GameServices/Modules/UI/Controls/ModuleMenuItem.cs
  Blish HUD/ref/common/157330 - Copy.png
Labels: cleanup

#833 Contingency Popup Improvements
  Blish HUD/GameServices/Debug/ContingencyPopup.Designer.cs
  Blish HUD/GameServices/Debug/ContingencyPopup.cs
Labels: bug

#835 API and Update Stability
  Blish HUD/GameServices/Gw2WebApi/TokenBucket.cs
  Blish HUD/GameServices/Overlay/SelfUpdater/SelfUpdateUtil.cs
Labels: bug

#836 Fix Gw2 paths.
  Blish HUD/_Utils/DirectoryUtil.cs
Labels: bug
