Repository blish-hud/Blish-HUD, pull requests merged in 2024-04, with the labels that each got.

#953 Include current version in update check.
  Blish HUD/GameServices/Overlay/OverlayUpdateHandler.cs
Labels: feature

#958 feat: add ModuleLoaded event to ModuleManager
  Blish HUD/GameServices/Modules/ModuleManager.cs
Labels: bug, feature

#961 Fixed self update for certain zip files.
  Blish HUD/GameServices/Overlay/SelfUpdater/SelfUpdateUtil.cs
Labels: bug
