Repository blish-hud/Blish-HUD, pull requests merged in 2024-05, with the labels that each got.

#965 feat: add IsAvailableChanged event to Gw2MumbleService
  Blish HUD/GameServices/Gw2MumbleService.cs
Labels: feature

#967 remove debug log message with api key
  Blish HUD/GameServices/Gw2WebApiService.cs
Labels: cleanup

#962 Added update notice in the about window.
  Blish HUD/GameServices/Overlay/OverlayUpdateHandler.cs
  Blish HUD/GameServices/Overlay/UI/Views/AboutView.cs
Labels: feature

#968 Resolve edge case when primary key is technically a modifier.
  Blish HUD/GameServices/Input/Keyboard/KeyBinding.cs
Labels: bug
